language: go

sudo: false
go:
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/golang/lint/golint
    - pip install --user codecov
    - go get github.com/fzipp/gocyclo

install:
    - go get -v ./...
    - go vet ./...
    - test -z "$($HOME/gopath/bin/golint ./... | tee /dev/stderr)"
    - gocyclo -over 15 .
    - go build -v ./...

script:
    - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
    - codecov
